Added option to delete created scenarii, add scenario to favourite, a…
sadikuar/Wizardery pull request #92
Opened 2020-04-10 16:25 UTC by nicopraz

…nd see favourite scenarios and rpgs to profile

2020-04-10 16:36 UTC, NicolasMinnig submitted a review, later dismissed

2020-04-10 18:45 UTC, ex-alor requested changes

2020-04-10 18:45 UTC, sadikuar commented on src/main/java/com/example/demo/controllers/ScenarioController.java
> +		System.out.println("HAS FAVOURITE");
Enlever le `sysout` si il n'est plus nécessaire

2020-04-11 07:37 UTC, ex-alor approved these changes

2020-04-11 07:37 UTC, merged